basePath: /
definitions:
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      fullname:
        type: string
      id:
        type: integer
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:80
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: You can visit the GitHub repository athttps://github.com/aldiset/online_store
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Online Store
  version: "1.0"
paths:
  /user:
    get:
      operationId: get-all-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: get all user
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
